[zkevm]
name = "ZisK"
protocol_family = "FRI_STARK"
version = "0.15.0"
field = "Goldilocks^3"
hash_size_bits = 256

[[circuits]]
name = "Main"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 146
opening_points = 3
batch_size = 61
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.006333333333333333

[[circuits]]
name = "Rom"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 2
num_columns = 3
opening_points = 3
batch_size = 18
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005

[[circuits]]
name = "Mem"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 34
opening_points = 3
batch_size = 29
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005666666666666667

[[circuits]]
name = "RomData"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = 23
opening_points = 3
batch_size = 19
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.004333333333333333

[[circuits]]
name = "InputData"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = 26
opening_points = 3
batch_size = 27
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.004666666666666667

[[circuits]]
name = "MemAlign"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = 40
opening_points = 3
batch_size = 59
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005666666666666667

[[circuits]]
name = "MemAlignByte"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 16
opening_points = 3
batch_size = 25
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005333333333333333

[[circuits]]
name = "MemAlignReadByte"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 10
opening_points = 3
batch_size = 18
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005

[[circuits]]
name = "MemAlignWriteByte"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 15
opening_points = 3
batch_size = 23
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005333333333333333

[[circuits]]
name = "Arith"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = 65
opening_points = 3
batch_size = 64
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005666666666666667

[[circuits]]
name = "Binary"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 14
opening_points = 3
batch_size = 49
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005999999999999999

[[circuits]]
name = "BinaryAdd"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 9
opening_points = 3
batch_size = 18
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005

[[circuits]]
name = "BinaryExtension"
group = "basic"
trace_length = 4194304
rho = 0.5
air_max_degree = 3
num_columns = 8
opening_points = 3
batch_size = 40
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005999999999999999

[[circuits]]
name = "Add256"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = 36
opening_points = 3
batch_size = 69
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 64
grinding_query_phase = 16
gap_to_radius = 0.005

[[circuits]]
name = "ArithEq"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = 93
opening_points = 36
batch_size = 434
power_batching = true
num_queries = 231
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 64
grinding_query_phase = 16
gap_to_radius = 0.007333333333333333

[[circuits]]
name = "ArithEq384"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = 76
opening_points = 54
batch_size = 536
power_batching = true
num_queries = 232
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 64
grinding_query_phase = 16
gap_to_radius = 0.007666666666666666

[[circuits]]
name = "Keccakf"
group = "basic"
trace_length = 131072
rho = 0.5
air_max_degree = 3
num_columns = 2432
opening_points = 26
batch_size = 4065
power_batching = true
num_queries = 217
fri_folding_factors = [8, 8, 8, 8]
fri_early_stop_degree = 64
grinding_query_phase = 23
gap_to_radius = 0.007333333333333333

[[circuits]]
name = "Sha256f"
group = "basic"
trace_length = 262144
rho = 0.5
air_max_degree = 3
num_columns = 115
opening_points = 87
batch_size = 1265
power_batching = true
num_queries = 231
fri_folding_factors = [8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.006666666666666666

[[circuits]]
name = "SpecifiedRanges"
group = "basic"
trace_length = 1048576
rho = 0.5
air_max_degree = 3
num_columns = 18
opening_points = 3
batch_size = 88
power_batching = true
num_queries = 229
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 64
grinding_query_phase = 16
gap_to_radius = 0.005333333333333333

[[circuits]]
name = "VirtualTable0"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = 6
opening_points = 3
batch_size = 69
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005666666666666667

[[circuits]]
name = "VirtualTable1"
group = "basic"
trace_length = 2097152
rho = 0.5
air_max_degree = 3
num_columns = 6
opening_points = 3
batch_size = 90
power_batching = true
num_queries = 230
fri_folding_factors = [8, 8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 16
gap_to_radius = 0.005999999999999999

[[circuits]]
name = "ArithEq-compressor"
group = "compression"
trace_length = 262144
rho = 0.25
air_max_degree = 5
num_columns = 179
opening_points = 6
batch_size = 198
power_batching = true
num_queries = 110
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 20
gap_to_radius = 0.004666666666666667

[[circuits]]
name = "ArithEq384-compressor"
group = "compression"
trace_length = 262144
rho = 0.25
air_max_degree = 5
num_columns = 179
opening_points = 6
batch_size = 198
power_batching = true
num_queries = 110
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 20
gap_to_radius = 0.004666666666666667

[[circuits]]
name = "Keccakf-compressor"
group = "compression"
trace_length = 1048576
rho = 0.25
air_max_degree = 5
num_columns = 179
opening_points = 6
batch_size = 198
power_batching = true
num_queries = 110
fri_folding_factors = [8, 8, 8, 8, 8, 4]
fri_early_stop_degree = 32
grinding_query_phase = 20
gap_to_radius = 0.006333333333333333

[[circuits]]
name = "Sha256f-compressor"
group = "compression"
trace_length = 524288
rho = 0.25
air_max_degree = 5
num_columns = 179
opening_points = 6
batch_size = 198
power_batching = true
num_queries = 110
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 64
grinding_query_phase = 20
gap_to_radius = 0.005333333333333333

[[circuits]]
name = "Recursive2"
group = "aggregation"
trace_length = 131072
rho = 0.125
air_max_degree = 8
num_columns = 158
opening_points = 4
batch_size = 145
power_batching = true
num_queries = 73
fri_folding_factors = [8, 8, 8, 8, 8]
fri_early_stop_degree = 32
grinding_query_phase = 20
gap_to_radius = 0.004

[[circuits]]
name = "Final"
group = "final"
trace_length = 65536
rho = 0.03125
air_max_degree = 8
num_columns = 160
opening_points = 4
batch_size = 152
power_batching = true
num_queries = 43
fri_folding_factors = [16, 16, 16]
fri_early_stop_degree = 512
grinding_query_phase = 22
gap_to_radius = 0.003333333333333333
